name: CI - Quality Gates

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true

      - name: Verify dependencies
        run: go mod verify

      - name: Check dependencies are tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
            echo "❌ go.mod or go.sum needs to be updated"
            git diff go.mod go.sum
            exit 1
          fi

      - name: Run go fmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "❌ Code is not formatted properly"
            gofmt -l .
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Build application
        run: go build -v ./...

      # Placeholder for when you add tests
      # - name: Run tests
      #   run: go test -v ./...

  # Prevent merging if quality checks fail
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: quality-checks
    if: always()
    
    steps:
      - name: Check quality gate status
        run: |
          if [ "${{ needs.quality-checks.result }}" != "success" ]; then
            echo "❌ Quality checks failed - blocking merge"
            exit 1
          else
            echo "✅ Quality checks passed"
          fi
